spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:default}
    password: ${SPRING_DATASOURCE_PASSWORD:default}
    url: ${SPRING_DATASOURCE_URL:default}

  data:
    redis:
      port: 6379
      host: redis

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:default_username}
    password: ${SPRING_MAIL_PASSWORD:default_password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081


jwt:
  secret: ${SPRING_JWT_SECRET:default}



