spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:default}
    password: ${SPRING_DATASOURCE_PASSWORD:default}
    url: ${SPRING_DATASOURCE_URL:default}

  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: ${SPRING_DATA_REDIS_HOST:localhost}

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:default_username}
    password: ${SPRING_MAIL_PASSWORD:default_password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  liquibase:
    change-log: classpath:/db/changelog/appchange-log.xml
    liquibase-schema: ${SPRING_LIQUIBASE_SCHEMA:default}

server:
  port: 8081

jwt:
  secret: ${SPRING_JWT_SECRET:default}

frontend:
  url: ${FRONTEND_URL:default}



