spring:
  datasource:
    username: root
    password: Manh2004
    url: jdbc:mysql://localhost:3306/shop_ttcs

  jpa:
    hibernate:
      ddl-auto: update
    #      none, update, auto-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
server:
  port: 8081
