spring:
  datasource:
    username: root
    password: Manh2004
    url: jdbc:mysql://localhost:3306/shop_ttcs

  jpa:
    hibernate:
      ddl-auto: update
    #      none, update, auto-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 587527461162-a54m3ptl5h91pp5qtvs826kqscgamifm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
server:
  port: 8081

path_private_key: private_key_pkcs8.pem
path_public_key: public_key.pem

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG

