spring:
  datasource:
    username: root
    password: Manh2004
    url: jdbc:mysql://localhost:3306/shop_ttcs

  data:
    redis:
      port: 6379
      host: localhost
      password:
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none
    #      none, update, auto-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenmanhlc10@gmail.com
    password: aaof rvju disf hati
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  liquibase:
    change-log: classpath:/db/changelog/appchange-log.xml
    liquibase-schema: shop_ttcs

server:
  port: 8081

jwt:
  secret: IHog2o7M6EPmoJ4Y4WBiLbvbCJ+AnYe3C1VmUQdW4gg=

frontend:
  url: http://localhost:5173





